### ISSUE TITLE
Installation fails if the path to the assembly has spaces

### ISSUE THREAD

**Issue by Choran66** [caseymarquis/KC.InstallService#1]
If the path to the assembly has spaces a service installation will fail.

Changing line 39 of InstallService.cs to:
`if (!RunCmdProcess.RunProcess(bestInstallUtil.FullName, $"\"{execFilePath}\"", Path.GetFullPath(".\\"))) {`

Resolves the issue.

**Comment by caseymarquis** [comment]
I didn't expect anyone to actually use this! Just saw this notification today (two months too late). I'll look in to this when I'm back from vacation. My assemblies have spaces in their paths,  so I think I was putting the quotes on during input or something like that. I'll have to trim quotes then add them to avoid double quotes in that case. 

Edit: Looking closer the issue is spaces to the. Net assembly. Either way I'll resolve this when back in the US.
